spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    serialization-inclusion: false
  datasource:
    driver: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: ${spring.datasource.master.url}
    username: ${spring.datasource.master.username}
    password: ${spring.datasource.master.password}
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 20000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      max-pool-prepared-statement-per-connection-size: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,wall,log4j
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.jdbc.Driver
  activemq:
    broker-url: ${spring.activemq.brokerurl}
    inMemory: true
    pool:
     enabled: true
     max-connections: 20
  # Redis服务器配置
  redis:
    host: ${spring.redis.host}
    # Redis服务器连接端口
    port: ${spring.redis.port}
    # Redis服务器连接密码
    password: ${spring.redis.password}
    #连接超时时间（毫秒）
    timeout: 30000ms
    jedis:
      # Redis服务器连接池
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        maxIdle: 100
        #连接池中的最小空闲连接
        minIdle: 50
        #连接池中的最大空闲连接
        maxActive: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        maxWait: -1ms
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/**/*Dao.xml
slave:
  datasource:
    names: ds1,ds2
    ds1:
      driver: com.mysql.jdbc.Driver
      url: ${spring.datasource.slave.url}
      username: ${spring.datasource.slave.username}
      password: ${spring.datasource.slave.password}
    ds2:
      driver: com.mysql.jdbc.Driver
      url: ${spring.datasource.slave.url}
      username: ${spring.datasource.slave.username}
      password: ${spring.datasource.slave.password}